### ISSUE TITLE
InvalidCastException

### ISSUE THREAD

**Issue by EasyRhinoMSFT** [ErikEJ/EntityFramework6PowerTools#72] opened 2020-08-18 15:23 UTC
I get this exception from any of the commands in this extension:
System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.VisualStudio.Shell.Interop.IVsAggregatableProject'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{FFB2E715-7312-4B93-83D7-D37BCC561C90}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at Microsoft.DbContextPackage.Extensions.ProjectExtensions.GetProjectTypes(Project project)
   at Microsoft.DbContextPackage.Extensions.ProjectExtensions.IsWebProject(Project project)
   at Microsoft.DbContextPackage.DbContextPackage.GetUserConfig(Project project, String assemblyFullName)
   at Microsoft.DbContextPackage.DbContextPackage.DiscoverUserContextType(Type& systemContextType)

Microsoft Visual Studio Enterprise 2019
Version 16.7.1

**Comment by ErikEJ** [comment] 2020-08-18 15:57
Duplicate of #62

**Closed** 2020-08-18 15:57 UTC
