### ISSUE TITLE
Reverse Engineering does not start

### ISSUE THREAD

**Issue by ronaldpschutte** [ErikEJ/EntityFramework6PowerTools#89] opened 2021-12-01 10:56 UTC
System.Exception: Table list error: 
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'C:\Users\me\AppData\Local\Temp\efreveng6.2.5.832.0\efreveng60.dll'. An attempt was made to load a program with an incorrect format.
File name: 'C:\Users\me\AppData\Local\Temp\efreveng6.2.5.832.0\efreveng60.dll'

   at List<TableModel> EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildTableResult(string output)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesInternalAsync(string arguments)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetTablesAsync(string connectionString, DatabaseType databaseType, SchemaInfo[] schemas)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.TableListBuilder.GetTableDefinitionsAsync(CodeGenerationMode codeGenerationMode)
   at async Task<List<TableModel>> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.GetTablesAsync(DatabaseConnectionModel dbInfo, CodeGenerationMode codeGenerationMode, SchemaInfo[] schemas)
   at async Task<bool> EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.LoadDataBaseObjectsAsync(ReverseEngineerOptions options, DatabaseConnectionModel dbInfo, Tuple<List<Schema>, string> namingOptionsAndPath)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate)

I have removed all efre folders as suggested in https://githubmemory.com/repo/ErikEJ/EFCorePowerTools/issues/980, but unfortunatly that did not help.

**Comment by ronaldpschutte** [comment] 2021-12-01 11:31
Could it be that it is trying to load a 32 bit in 64 bit now?

**Comment by ErikEJ** [comment] 2021-12-01 12:14
You are in the wrong repository, duplicate of https://github.com/ErikEJ/EFCorePowerTools/issues/1141#issuecomment-945709906

**Closed by ErikEJ** 2021-12-01 12:14 UTC
